#!/bin/bash
#
# bootstrap
#
# Checks for dependencies so you can get rolling with ActiveCell straight away

echo ""
echo "tabestakes.js"
echo "A bad-ass interactive grid platform."
echo ""

#
# Check for node
#
if test ! $(which node); then
  echo "  x You need to install node. If you use Homebrew, you can run:"
  echo "    brew install node"
  exit
else
  echo "  + node found."
fi

#
# Check for npm
#
if test ! $(which npm); then
  echo "  x You need to install npm. If you use Homebrew, you can run:"
  echo "    brew install npm"
  exit
else
  echo "  + npm found."
fi

#
# Check for coffee-script
#
if test ! $(which coffee); then
  echo "  x You need to install coffee. You can run:"
  echo "    npm install -g coffee-script"
  exit
else
  echo "  + coffee-script found."
fi

#
# Check for casperjs
#
if test ! $(which casperjs); then
  echo "  x You need to install casperjs. If you use Homebrew, you can run:"
  echo "    brew install casperjs"
  exit
else
  echo "  + casperjs found."
fi

#
# Install from package file
#
echo ""
echo "Installing packages from package.json."
npm install
