#!/bin/bash
#
# bootstrap
#
# Checks for dependencies so you can get rolling with ActiveCell straight away

echo ""
echo "  tactile.js"
echo "  A bad-ass interactive charting platform."
echo ""

#
# Check for node
#
if test ! $(which node); then
  echo "  x You need to install node. If you use Homebrew, you can run:"
  echo "    brew install node"
  exit
else
  echo "  + node found."
fi

#
# Check for npm
#
if test ! $(which npm); then
  echo "  x You need to install npm. If you use Homebrew, you can run:"
  echo "    brew install npm"
  exit
else
  echo "  + npm found."
fi

#
# Check for grunt
#
if test ! $(which grunt); then
  echo "  x You need to install grunt. If you use Homebrew, you can run:"
  echo "    brew install grunt"
  exit
else
  echo "  + grunt found."
fi

#
# Check for grunt
#
if test ! $(which compass); then
  echo "  x You need to install compass. If you use gems, you can run:"
  echo "    gem install compass"
  exit
else
  echo "  + compass found."
fi

#
# Install from package file
#
echo "Installing from package.json."
npm install

#
# Install gems
#
echo "Installing ruby gems."
bundle

#
# Build
#
echo "Performing sample build."
grunt build